#====================================================================================================
layer1:

  paths:
    RANDOM_TRAJECTORIES_FOLDER : "generatedData/2dL1/csv/"
    TRAJECTORIES_FOLDER : "generatedData/2dL1/" 
    INT_TRAJECTORIES_FOLDER : "generatedData/2dL1INT/" 
    TRAJECTORIES_3D_FOLDER : "generatedData/3dL2/csv/"
    STD_MAZE : "maze2d_004.npy"
    FIGS_FOLDER : "generatedFigs"

  settings:
    SEED : 234
    OUT_FORMAT : "csv" # (csv or npy)

    N_TRAJECTORIES_TO_GENERATE : 99 # Number of UAV Trajectories
    TRAJECTORIES_BUFFER_SIZE : 3 # Number UAV past trajectories recorded (to be then horizontally separated)
    SCALE_SIZE : 20 # length of cell side in meters unit

    NROWS : 43
    NCOLS : 43

    # Learning related constants   
    MIN_EXPLORE_RATE : 0.001
    MIN_LEARNING_RATE : 0.2

    # Defining the simulation related constants
    MAX_T : 10000
    STREAK_TO_END : 100
    SOLVED_T : 10
  
    # Plotting constants
    doSave_3dPlot : True
    exploded_3dPlot : True
    doSave_xyPlot : True

  vertical_separation:
    MIN_HEIGHT : 50
    MAX_HEIGHT : 300
    SEP_H  :  10
    RADIUS : 50 #m
    TOLERANCE : 0.0


#====================================================================================================
layer2:

#====================================================================================================
layer3: