#====================================================================================================
# CONFIG file containing paths and global variable

# format: <variable> : value 
#  <#> for comments
# space after double dots is needed


paths:
  AIRSIM_SETTINGS_FILE : "settings.json"
  #'C:\Users\gioca\OneDrive\Documents\AirSim\settings.json'
  # TODO since inconsistent (it's just a copy) change for real or use this in airsim
  Q_TRAJECTORIES : "./qtrajectories/"

  LAYER1_INPUT_STARTS_FILE: "inputData/start_pos_table.csv"
  LAYER1_INPUT_GOALS_FILE: "inputData/goal_pos_table.csv"
  
  LAYER1_2D_OUTPUT_FOLDER : "generatedData/2dL1/" 
  LAYER1_2D_INTERPOLATED_OUTPUT_FOLDER : "generatedData/2dL1INT/" 
  LAYER1_3D_OUTPUT_FOLDER : "generatedData/3dL1/"
  
  LAYER2_OUTPUT_FOLDER : "generatedData/3dL2/"

  LAYER3_OUTPUT_FOLDER : "generatedData/3dL3/"
  
  STD_MAZE : "maze2d_004.npy"
  LOG_FOLDER : "./generatedData/logs/"
  FIGS_FOLDER : "generatedFigs"
  EUROCONTROL_FOLDER : "generatedData/eurocontrol/"

layer1:
  settings:
    SEED : 234 # -1 for casual seed
    OUT_FORMAT : "csv" # (csv or npy) for layer1 output

    N_TRAJECTORIES_TO_GENERATE : 99 # Number of UAV Trajectories
    TRAJECTORIES_BUFFER_SIZE : 3 # Number UAV past trajectories recorded (to be then horizontally separated)
    SCALE_SIZE : 40 # length of cell side in meters unit

    # Influence when --generate-maze arg is passed
    NROWS : 43
    NCOLS : 43
    OBS_BLOCKS : 6
    
    # Learning related constants   
    EPISODES: 500
    MIN_EXPLORE_RATE : 0.001
    MIN_LEARNING_RATE : 0.2
    NSTEPS : 0
    
    # Defining the simulation related constants
    MAX_T : 10000
    STREAK_TO_END : 100
    SOLVED_T : 10
  
    # Plotting constants
    doSave_3dPlot : True
    exploded_3dPlot : True
    doSave_xyPlot : True

  
  vertical_separation:
    MIN_HEIGHT : 50
    MAX_HEIGHT : 300
    SEP_H  :  10
    RADIUS : 50 #m
    TOLERANCE : 0.0


#====================================================================================================
layer2:
    #UAV default velocity (Airsim)
    VELOCITY : 12
    AIRSIM_SAMPLING_INTERVAL: 0.01 #in seconds
    
    #Values to correct trajectory 
    W_SCALE : 1
    H_SCALE : 1
    W_OFFSET : -14
    H_OFFSET : -14
#====================================================================================================
layer3:
    #UAV default velocity (Airsim)
    SHOW_XY_PLOT : False 
    VELOCITY : 12
    FIXED_Z : -100 # Negative due to airsim
    SRID : "EPSG:5555"
    ORIGIN : 
      - x : 2.174432
      - y : 41.404572
      - z : 0
    O_THETA : 0
